install go ooo

diff --git a/.openshift/action_hooks/build b/.openshift/action_hooks/build
--- a/.openshift/action_hooks/build
+++ b/.openshift/action_hooks/build
@@ -1,11 +1,12 @@
 #!/bin/bash
 
-set -e
-
 # Install go
 # We expect the output of `go version` to be something like
 # "go version go1.1.2 darwin/amd64"
 GO_VERSION=`go version | awk '{split($0,a," "); print a[3]}'`
+
+set -e # exit upon error
+
 if [ $GO_VERSION != 'go1.1.2' ]; then
   curl https://go.googlecode.com/files/go1.1.2.linux-amd64.tar.gz |
   tar zxf - -C $OPENSHIFT_DATA_DIR
